# 1. Read Dataset

In [1]:
import pandas as pd

In [2]:
# Read all the data from csv file
def read_dataset(file_path):
    names = ['airline_sentiment', 'text']
    data = pd.read_csv(file_path, names = names, header=0)
    return data

In [3]:
def read_train_test_data(dir='Data'):
    train_data = read_dataset(dir + "/train.csv")
    test_data = read_dataset(dir + "/test.csv")
    return train_data, test_data

In [4]:
def sep_text_sentiment(data):
    return data.iloc[:, 1].values.tolist(), data.iloc[:, 0].values.tolist()

# 2. Data Cleaning

### 2.1. Remove hashtags

In [5]:
# Remove the hashtags from the data #xyz
def remove_hashtags(data):
    return [re.sub(r'#\w+ ?', '', text) for text in data]

### 2.2. Remove User mentions

In [6]:
# Remove the user mentions from the data @xyz
def remove_um(data):
    return [re.sub(r'@\w+ ?', '', text) for text in data]

### 2.3. Remove urls

In [7]:
# Remove the urls from the data
def remove_urls(data):
    return [re.sub(r'http\S+', '', text) for text in data]

### 2.4. Remove Stop words

In [8]:
import nltk
import re
nltk.download("stopwords")
from nltk.corpus import stopwords
stop = stopwords.words('english')

[nltk_data] Downloading package stopwords to /home/usama/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [9]:
def rem_stop_words(data):
    return [" ".join(text for text in text.split() if text not in stop) for text in data]

### 2.5. Remove Punctuations

In [10]:
def rem_punc(data):
    return [re.sub(r'[^\w\s]', '', text) for text in data]

### 2.6. Remove numbers

In [11]:
def rem_nums(data):
    return [re.sub('\d+', '', text) for text in data]
    

### 2.7 Lower case data 

In [12]:
def lower(data):
    return [text.lower() for text in data]

### 2.8. Split texts to tokens

In [13]:
def bow(data):
    return [text.split() for text in data]

### 2.9. Apply all to clean data

In [14]:
def clean_data(data):
    data = remove_hashtags(data)
    data = remove_um(data)
    data = remove_urls(data)
    data = rem_stop_words(data)
    data = rem_punc(data)
    data = rem_nums(data)
    data = lower(data)
#     data = bow(data)
    return data

In [15]:
def tfidf_vec(data):
    from sklearn.feature_extraction.text import TfidfVectorizer
    
    # create the transform
    vectorizer = TfidfVectorizer(max_features=2500, min_df=7, max_df=0.8)
    # Tokenize and build
    return vectorizer.fit_transform(data).toarray()

In [16]:
# def skipgram_w2v(data):
#     from gensim.models import Word2Vec
#     # training the model
#     skipgram = Word2Vec(data, window = 3, min_count=1, sg = 1)
#     return skipgram

In [17]:
# def save_model(model, file='skipgram.bin'):
#     model.save(file)

In [18]:
# def load_model(file='skipgram.bin'):
#     return Word2Vec.load(file)

In [16]:
def save_model(model, file='finalized_model.sav'):
    import pickle
    pickle.dump(model, open(file, 'wb'))

In [17]:
def load_model(file='finalized_model.sav'):
    import pickle
    return pickle.load(open(file, 'rb'))

In [366]:
def main():
    from sklearn.ensemble import RandomForestClassifier
    
    # Reading Dataset
    train_data, test_data = read_train_test_data()
    train_texts, train_sentiment = sep_text_sentiment(train_data)
    test_texts, test_sentiment = sep_text_sentiment(test_data)
    
    # Cleaning Data
    train_texts = clean_data(train_texts)
    test_texts = clean_data(test_texts)
    
    train_skipgram = skipgram_w2v(train_texts)
    test_skipgram = skipgram_w2v(test_texts)
#     save_model(train_skipgram)
#     train_skipgram = load_model()
    train_skipgram = (tfidf_vec(train_texts))
    
#     train_skipgram = np.array(train_skipgram)
    text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
    text_classifier.fit(train_skipgram, train_sentiment)
    
    text_classifier.predict("I have no choice but to fly Southwest to Vega")
#     test_skipgram = (tfidf_vec(test_texts))
#     text_classifier.fit(test_skipgram, test_sentiment)
#     predictions = text_classifier.predict(test_skipgram)
    
    
    from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

    print(confusion_matrix(test_sentiment,predictions))
    print(classification_report(test_sentiment,predictions))
    print(accuracy_score(test_sentiment, predictions))

In [367]:
if __name__ == "__main__":
    main()

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


KeyboardInterrupt: 

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# # Reading Dataset
train_data, test_data = read_train_test_data()
train_texts, train_sentiment = sep_text_sentiment(train_data)
test_texts, test_sentiment = sep_text_sentiment(test_data)

# Cleaning Data
train_texts = clean_data(train_texts)
test_texts = clean_data(test_texts)

# train_skipgram = skipgram_w2v(train_texts)
# test_skipgram = skipgram_w2v(test_texts)
# train_skipgram = tfidf_vec(train_texts)
# train_skipgram = load_model()

# Train the model
text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(train_skipgram, train_sentiment)
# save_model(text_classifier)


# text_classifier.predict("I have no choice but to fly Southwest to Vega")
test_skipgram = tfidf_vec(test_texts)
# text_classifier.fit(test_skipgram, test_sentiment)
# predictions = text_classifier.predict(test_skipgram)

# print(confusion_matrix(test_sentiment,predictions))
# print(classification_report(test_sentiment,predictions))
# print(accuracy_score(test_sentiment, predictions))

NameError: name 'train_skipgram' is not defined

In [19]:
model = load_model()
# test_skipgram = model.transform(test_skipgram)
new_tfidf = model.transform(test_skipgram)
# test_skipgram = (tfidf_vec(test_skipgram))
predictions = model.predict(test_skipgram)

AttributeError: 'RandomForestClassifier' object has no attribute 'transform'

In [24]:
from sklearn.feature_extraction.text import CountVectorizer

data =  train_texts + test_texts
sent = train_sentiment + test_sentiment
vectorizer = CountVectorizer()

features = vectorizer.fit_transform(data)
features_nd = features.toarray() # for easy usage

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test  = train_test_split(
        features_nd, 
        sent,
        train_size=0.80, 
        random_state=1234)


In [25]:
text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X=X_train, y=y_train)

y_pred = text_classifier.predict(X_test)


In [27]:
import random
j = random.randint(0,(len(X_test))-10)
for i in range(j,j+10):
    print(y_pred[i])
    ind = features_nd.tolist().index(X_test[i].tolist())
    print(ind)
    print(data[ind])


1
6844
sorry i ended us air flight thank though getting back me
0
8923
hopefully nashville open i want come home today
1
7398
holy high speed internet batman speeds united club iad insanely fast thanks
2
4918
i know probably way get cheaper airfare ticket flight leaving hours 
0
11563
hold  hours cancelled flighted flight i understand delay i understand autoreflight booking problems tuesday help
0
6037
can help get flight tonight houstonjust want stuck till monday bad weather moving
0
3055
mellani b whole team columbia sc absolute superstars incredibly helpful
1
2080
thanks much talking me the article chats came great
0
2635
whole plane hoping better luck return flight sunday
0
14512
prime ticketed seat get switched aa  not sure whats going here


In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))


0.7646857923497268


In [29]:
count = 0.0
for i in range(len(y_test)):
    if y_pred[i] == y_test[i]:
        count += 1

        
print(count/len(y_test))

0.7646857923497268


In [55]:
from sklearn.preprocessing import LabelEncoder

text = "hi i am ok"
cv_new = CountVectorizer(
        stop_words='english',
        strip_accents='unicode',
        lowercase=True,
        vocabulary=vectorizer.vocabulary_
        )
prediction = ""
matrix = vectorizer.fit_transform([text])
matrix = matrix.reshape(1, -1)
encoder = LabelEncoder()
labels = encoder.fit_transform(sent)
rf = RandomForestClassifier()
rf.fit(matrix, labels)
# matrix = matrix.reshape(1, -1)
try:
    prediction = rf.predict(matrix)
except Exception as E:
    print(str(E))
else:
    prediction = Predict_Label("really", cv_new, rf)
print(prediction)

# text_classifier.predict(text)

ValueError: Number of labels=14640 does not match number of samples=1

In [38]:
len(features_nd[100])

10998

In [41]:
vectorizer.vocabulary_

{'really': 7749,
 'aggressive': 219,
 'blast': 1057,
 'obnoxious': 6598,
 'entertainment': 3193,
 'guests': 4247,
 'faces': 3444,
 'amp': 387,
 'little': 5602,
 'recourse': 7811,
 'this': 9666,
 'great': 4179,
 'deal': 2437,
 'already': 341,
 'thinking': 9662,
 'nd': 6371,
 'trip': 9968,
 'thanks': 9608,
 'so': 8922,
 'excited': 3336,
 'first': 3625,
 'cross': 2261,
 'country': 2172,
 'flight': 3676,
 'lax': 5422,
 'mco': 5915,
 'ive': 5099,
 'heard': 4388,
 'nothing': 6529,
 'things': 9655,
 'virgin': 10418,
 'america': 373,
 'love': 5713,
 'hipster': 4488,
 'innovation': 4908,
 'you': 10948,
 'feel': 3549,
 'good': 4130,
 'brand': 1198,
 'making': 5807,
 'bosgt': 1149,
 'miss': 6135,
 'me': 5927,
 'dont': 2875,
 'worry': 10823,
 'well': 10622,
 'together': 9806,
 'soon': 8965,
 'hi': 4462,
 'bked': 1041,
 'cool': 2118,
 'birthday': 1024,
 'cant': 1440,
 'add': 124,
 'elevate': 3082,
 'no': 6470,
 'cause': 1512,
 'entered': 3186,
 'middle': 6046,
 'name': 6326,
 'booking': 1122,
 'pro

In [62]:
yt_pred = text_classifier.predict(X_train)

In [63]:
print(accuracy_score(y_train, yt_pred))


0.9943647540983607
